# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 097223d602325bbe64cd1fb53ed6878adea2cabb3bba23fe8120f93502960f3a101bd2846f729150982df2f40227d7076207e6f44cb8244751bbcc2991253f67

test:
  secret_key_base: a77208702a2107da2d238e48c1a085d660e394a017e1923a25ba182a6435ddfe00ee7a93e2a98ed3906a48c73c1c27633d4fd8c2d27c06d6613a5bf6599cfec5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
